[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"
transaction_hash = "0x7f1456c94b5cc20a043c7acb7e183a31b57b6de82699b062498189f8aae9d0b"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x554eddebb282c17b8dce34c01ed146a67d96c39d8ca5c1d09d32188fb79d37c"
class_hash = "0x65926fe827d0c09b35ea07d98b442d9823b21dc419af042321896557d041f32"
original_class_hash = "0x65926fe827d0c09b35ea07d98b442d9823b21dc419af042321896557d041f32"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_lobby_lobby.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::lobby::lobby"

[[contracts]]
kind = "DojoContract"
address = "0x7200d12110039afe4e58f21540f901670e5637717fd567f89294d999c03b9a9"
class_hash = "0x799fa2c71394df65cb43a2c1f1088cad76309a965719e5d40307d069a10f8dc"
original_class_hash = "0x799fa2c71394df65cb43a2c1f1088cad76309a965719e5d40307d069a10f8dc"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_registry_registry.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::registry::registry"

[[models]]
kind = "DojoModel"
class_hash = "0x641d7d3c7220db7fff926fc107cf6cbae2f10b8c4b15782909fcc6d9220607f"
original_class_hash = "0x641d7d3c7220db7fff926fc107cf6cbae2f10b8c4b15782909fcc6d9220607f"
abi = "abis/deployments/models/dojo_starter_models_game_game.json"
name = "dojo_starter::models::game::game"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "player_a_active_slot"
type = "u8"
key = false

[[models.members]]
name = "player_b_active_slot"
type = "u8"
key = false

[[models.members]]
name = "turn"
type = "u16"
key = false

[[models.members]]
name = "game_status"
type = "GameStatus"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "winner_slot"
type = "u8"
key = false

[[models.members]]
name = "turn_expiry"
type = "u64"
key = false

[[models.members]]
name = "challenge_expiry"
type = "u64"
key = false

[[models.members]]
name = "total_turn_time"
type = "u64"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4ec1f85ba8ab622ef4d0845a60c45809ba06862b4fd8a8076b1c85475419dab"
original_class_hash = "0x4ec1f85ba8ab622ef4d0845a60c45809ba06862b4fd8a8076b1c85475419dab"
abi = "abis/deployments/models/dojo_starter_models_game_poke_in_game.json"
name = "dojo_starter::models::game::poke_in_game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "slot"
type = "u8"
key = true

[[models.members]]
name = "pokemon_id"
type = "u32"
key = false

[[models.members]]
name = "lvl"
type = "u8"
key = false

[[models.members]]
name = "hp"
type = "u16"
key = false

[[models.members]]
name = "atk"
type = "u16"
key = false

[[models.members]]
name = "def"
type = "u16"
key = false

[[models.members]]
name = "spa"
type = "u16"
key = false

[[models.members]]
name = "spd"
type = "u16"
key = false

[[models.members]]
name = "spe"
type = "u16"
key = false

[[models.members]]
name = "move1"
type = "u16"
key = false

[[models.members]]
name = "move1_limit"
type = "u8"
key = false

[[models.members]]
name = "move2"
type = "u16"
key = false

[[models.members]]
name = "move2_limit"
type = "u8"
key = false

[[models.members]]
name = "move3"
type = "u16"
key = false

[[models.members]]
name = "move3_limit"
type = "u8"
key = false

[[models.members]]
name = "move4"
type = "u16"
key = false

[[models.members]]
name = "move4_limit"
type = "u8"
key = false

[[models.members]]
name = "side_effect1"
type = "SideEffect"
key = false

[[models.members]]
name = "side_effect2"
type = "SideEffect"
key = false

[[models.members]]
name = "side_effect3"
type = "SideEffect"
key = false

[[models.members]]
name = "side_effect4"
type = "SideEffect"
key = false

[[models.members]]
name = "status"
type = "PokeGameStatus"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3471fcd6c7743e035749bb863ec773ee48ffc550b92652c26b8c9cf63310682"
original_class_hash = "0x3471fcd6c7743e035749bb863ec773ee48ffc550b92652c26b8c9cf63310682"
abi = "abis/deployments/models/dojo_starter_models_game_turn.json"
name = "dojo_starter::models::game::turn"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "turn_status"
type = "u8"
key = true

[[models.members]]
name = "state"
type = "u8"
key = false

[[models.members]]
name = "move_a"
type = "GameMove"
key = false

[[models.members]]
name = "move_b"
type = "GameMove"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3072eefe19669381eadd321adef9b868f267adcf6065789c4503c001d5dcdd8"
original_class_hash = "0x3072eefe19669381eadd321adef9b868f267adcf6065789c4503c001d5dcdd8"
abi = "abis/deployments/models/dojo_starter_models_moves_gen_1_random_move_set.json"
name = "dojo_starter::models::moves::gen_1_random_move_set"

[[models.members]]
name = "poke_id"
type = "u32"
key = true

[[models.members]]
name = "move_1"
type = "u16"
key = false

[[models.members]]
name = "move_2"
type = "u16"
key = false

[[models.members]]
name = "move_3"
type = "u16"
key = false

[[models.members]]
name = "move_4"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3afdcf3ad31b70748e851bda321187c8a66b5703d115519bf20561af7db89ae"
original_class_hash = "0x3afdcf3ad31b70748e851bda321187c8a66b5703d115519bf20561af7db89ae"
abi = "abis/deployments/models/dojo_starter_models_moves_move_book.json"
name = "dojo_starter::models::moves::move_book"

[[models.members]]
name = "move_id"
type = "u16"
key = true

[[models.members]]
name = "accuracy"
type = "u8"
key = false

[[models.members]]
name = "basepower"
type = "u16"
key = false

[[models.members]]
name = "category"
type = "MoveCategory"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "pp"
type = "u16"
key = false

[[models.members]]
name = "priority"
type = "u8"
key = false

[[models.members]]
name = "secondary"
type = "u16"
key = false

[[models.members]]
name = "target"
type = "MoveTarget"
key = false

[[models.members]]
name = "moveSystemCallBack"
type = "u16"
key = false

[[models.members]]
name = "flags"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x13d706616881cba9e93681e11e2f2beb6dd4f7709f4b1cda0c324b0dec8cf57"
original_class_hash = "0x13d706616881cba9e93681e11e2f2beb6dd4f7709f4b1cda0c324b0dec8cf57"
abi = "abis/deployments/models/dojo_starter_models_player_lineup.json"
name = "dojo_starter::models::player::lineup"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "slot1"
type = "u32"
key = false

[[models.members]]
name = "slot2"
type = "u32"
key = false

[[models.members]]
name = "slot3"
type = "u32"
key = false

[[models.members]]
name = "slot4"
type = "u32"
key = false

[[models.members]]
name = "slot5"
type = "u32"
key = false

[[models.members]]
name = "slot6"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4983ea3f3a6779a4f36f5793a6d084102a757cb49ad267ea009f3c2c1acaaaf"
original_class_hash = "0x4983ea3f3a6779a4f36f5793a6d084102a757cb49ad267ea009f3c2c1acaaaf"
abi = "abis/deployments/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic"
type = "u16"
key = false

[[models.members]]
name = "total_duels"
type = "u16"
key = false

[[models.members]]
name = "total_wins"
type = "u16"
key = false

[[models.members]]
name = "total_losses"
type = "u16"
key = false

[[models.members]]
name = "ranking"
type = "u256"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7bc439b8efd06c767e031031919e48eb00eaded23ce0198e4262dd0e6800fa2"
original_class_hash = "0x7bc439b8efd06c767e031031919e48eb00eaded23ce0198e4262dd0e6800fa2"
abi = "abis/deployments/models/dojo_starter_models_pokemon_pokedex.json"
name = "dojo_starter::models::pokemon::pokedex"

[[models.members]]
name = "pokemon_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "randomlvl"
type = "u8"
key = false

[[models.members]]
name = "hp"
type = "u16"
key = false

[[models.members]]
name = "atk"
type = "u16"
key = false

[[models.members]]
name = "def"
type = "u16"
key = false

[[models.members]]
name = "spa"
type = "u16"
key = false

[[models.members]]
name = "spd"
type = "u16"
key = false

[[models.members]]
name = "spe"
type = "u16"
key = false
