kind = "DojoModel"
class_hash = "0x371aede8f794b03e800783520f91b1721ec92e56378219f420ec60b6c38f2b6"
original_class_hash = "0x371aede8f794b03e800783520f91b1721ec92e56378219f420ec60b6c38f2b6"
abi = "manifests/dev/abis/base/models/dojo_starter_models_moves_move_book.json"
name = "dojo_starter::models::moves::move_book"

[[members]]
name = "move_id"
type = "u16"
key = true

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "basepower"
type = "u16"
key = false

[[members]]
name = "category"
type = "MoveCategory"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "pp"
type = "u16"
key = false

[[members]]
name = "priority"
type = "u8"
key = false

[[members]]
name = "secondary"
type = "u16"
key = false

[[members]]
name = "target"
type = "MoveTarget"
key = false

[[members]]
name = "move_limit"
type = "u8"
key = false

[[members]]
name = "moveSystemCallBack"
type = "u16"
key = false

[[members]]
name = "flags"
type = "u16"
key = false
