kind = "DojoModel"
class_hash = "0x4765e33e9b636dac0aa09508055bbdab85ee16df13f89588082a58350b295e5"
original_class_hash = "0x4765e33e9b636dac0aa09508055bbdab85ee16df13f89588082a58350b295e5"
abi = "manifests/dev/abis/base/models/dojo_starter_models_game_turn.json"
name = "dojo_starter::models::game::turn"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "turn"
type = "u8"
key = true

[[members]]
name = "turn_status"
type = "TurnStatus"
key = false

[[members]]
name = "move_a"
type = "GameMove"
key = false

[[members]]
name = "move_b"
type = "GameMove"
key = false

[[members]]
name = "timestamp_start"
type = "u64"
key = false

[[members]]
name = "timestamp_end"
type = "u64"
key = false
