kind = "DojoModel"
class_hash = "0x3e832afbfbed229ba0c9f6dfde859889f20694a91e773960eca372b064fdea5"
original_class_hash = "0x3e832afbfbed229ba0c9f6dfde859889f20694a91e773960eca372b064fdea5"
abi = "manifests/dev/abis/base/models/dojo_starter_models_moves_gen_1_random_move_set.json"
name = "dojo_starter::models::moves::gen_1_random_move_set"

[[members]]
name = "blob_id"
type = "u32"
key = true

[[members]]
name = "move_1"
type = "u16"
key = false

[[members]]
name = "move_2"
type = "u16"
key = false

[[members]]
name = "move_3"
type = "u16"
key = false

[[members]]
name = "move_4"
type = "u16"
key = false
